sudo: required

language: php
php:
  # - '5.5'
  # - '5.6'
   - 7.1.5
   - 7.2
  #  - hhvm # on Trusty only
  #  - nightly

branches:
  only:
    master

# before_script:
#   - composer self-update
#   - composer install --prefer-source --no-interaction --dev

script:
   - vendor/bin/phpunit
   - phpunit --configuration phpunit.xml

notifications:
  email: false

